alias bat='upower -i $(upower -e | grep '/battery') | grep --color=never -E "state|to\ full|to\ empty|percentage"'
alias d='date'
alias c='clear'
alias gs='git status'
alias gd='git diff'
alias ga='git add -A'
